### ISSUE TITLE
[IMPROVEMENT] Upgrade Amazon Linux Support to Version 2

### ISSUE THREAD

**Issue by MatthiasScholz** [hashicorp/terraform-aws-nomad#18]
AWS update there Amazon Linux to a new version 2: https://aws.amazon.com/de/amazon-linux-2/

**Interesting Features:**
- systemd
- on-premise support ( Docker, ... )

**Outlook:**
The support of systemd would facilitate the setup and configuration of Nomad and Consul, as well.
Supervisor would not be needed anymore to streamline setup, since Debian and Ubuntu are using systemd as well.

**Question:**
Should the Amazon Linux 1 support be dropped?
1. Pro: Legacy support
2. Contra: Duplication of many configuration files, especially for the AMI creation.
3. Contra: Increased complexity in the `install-nomad` and `run-nomad` script.

_Suggestion:_
Drop support since the provided setup can only be seen as an example.

_Note:_
Once this is decided, I can provide a PR.

**Comment by brikis98** [comment]
I think it does make sense to switch to Amazon Linux 2, use systemd, and drop support for Amazon Linux 1. That said, I believe the version of Amazon Linux 2 out now is an LTS candidate, so perhaps it's worth waiting for the official LTS to come out?

**Comment by MatthiasScholz** [comment]
Current version is: Amazon Linux 2 LTS Candidate (2017.12) ( 2018-02-04 ).
I agree it might be better to wait for the official release before turning Amazon Linux 1 off. Currently no release date is announced.

What do you think about dropping the usage of supervisord to configure the Nomad and Consul services running on the nodes? Since systemd will basically be a general approach supported by many linux distributions, it could facilitate the handling.

**Comment by brikis98** [comment]
Yup, once the official LTS comes out, it makes sense to switch to systemd across the board: Consul, Nomad, Vault.

**Comment by MatthiasScholz** [comment]
Until the release will be there I will keep this feature branch updated:
[feature/amazonlinux2](https://github.com/MatthiasScholz/terraform-aws-nomad/tree/feature/amazonlinux2)

**Comment by SladeRun14** [comment]
No longer works with Amazon Linux 2.  The _install-nomad_ script needlessly expects `pip `to be installed, which isn't, so as to install `systemctl`, which is already installed.  Simply removing `sudo pip install supervisor` from _install-nomad_ fixes this for us since we only need to support Amazon Linux 2.

**Comment by brikis98** [comment]
We have switched our other repos from supservisor to systemd. See [this PR](https://github.com/hashicorp/terraform-aws-consul/pull/130) for an example. Anyone up for a PR to update this repo too?
