### ISSUE TITLE
ECR login

### ISSUE THREAD

**Issue by arshdeeptinna** [hashicorp/terraform-aws-nomad#31]
I am a nomad,  consul newbie and used these modules to create a new cluster. Can you please help me understand how to specify/create client config so that I can use ECR repository to move ECS tasks to nomad jobs.
I tried following nomad documentation but  found it lacking.

**Comment by josh-padnick** [comment]
There's nothing magical about using ECR with Nomad. ECR is just another Docker registry. The catch is that you're going to have to figure out how to authenticate your Nomad nodes to ECR. [This GitHub Issue comment](https://github.com/hashicorp/nomad/issues/3526#issuecomment-344200339) seems like one good way to do it.

**Comment by arshdeeptinna** [comment]
@josh-padnick I was wondering how we supply client docker config json file. Will it be part of userdata?

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-nomad/tree/master/modules/run-nomad#overriding-the-configuration

**Comment by Tethik** [comment]
Here's how I do it currently.

I use the following helper that I install on my AMI via Packer.
https://github.com/awslabs/amazon-ecr-credential-helper

Then inside the terraform user data script run for the nomad clients I do the following to write the
configuration.

```bash
sudo cat >/opt/nomad/config/client.hcl << EOF
client {
  enabled = true
  node_class = "${node_class}"
  options {
    "docker.auth.helper" = "ecr-login"
  }
}
EOF
```

Then via terraform I set up a IAM role policy to allow the client hosts for full read access the ECR
```tf
# Sets up policy to allow for ecr reads.
resource "aws_iam_role_policy" "staging-client-docker_ecr_policy" {
    name = "nomad-client-docker_ecr_policy"
    role = "${module.staging_clients.iam_role_id}"
    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
    {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage"
            ],
            "Resource": "*"
        }
    ]
}
EOF
}
```

**Comment by benbuzbee** [comment]
@Tethik's answer is great, but I didn't want to have to deal with 'go get' in an AMI so I did its basic job in this bash script. 

If you copy this to an executable file named /usr/local/bin/docker-credential-ecr-login

and follow the rest of Tethiks steps, it should work fine, without having to build another tool.

```
#!/bin/bash
# Docker credhelper script for running on EC2 instances
# https://docs.docker.com/engine/reference/commandline/login/#credential-helpers

AUTH_OBJ=$(AWS_DEFAULT_REGION="$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone 2> /dev/null | sed s/.$//)" aws ecr get-authorization-token)
BASIC=$(echo "$AUTH_OBJ" | jq -r '.authorizationData[0].authorizationToken' | base64 -d)
ENDPOINT=$(echo "$AUTH_OBJ" | jq -r '.authorizationData[0].proxyEndpoint')
jq --arg endpoint $ENDPOINT --arg user "$(echo $BASIC | sed s/:.*//)" --arg secret "$(echo $BASIC | sed s/.*://)" -r '{Username:$user, Secret:$secret, ServerURL:$endpoint}' <<< '{}'
```
