### ISSUE TITLE
Reference to tag 0.0.5 does not exist

### ISSUE THREAD

**Issue by dgrstl** [hashicorp/terraform-aws-nomad#7]
https://github.com/hashicorp/terraform-aws-nomad/blob/3ddcbc68b29d2c968166cfe45a9f1333a8038158/examples/nomad-consul-separate-cluster/main.tf#L99

**Comment by brikis98** [comment]
Ah, good catch. We moved these repos over recently and the move did not preserve previous releases. Fixed: https://github.com/hashicorp/terraform-aws-nomad/commit/223be6dfee91b7d94464609c65ae5a43ae6a1adb
