### ISSUE TITLE
Module nomad-cluster : aws_autoscaling_attachment broken

### ISSUE THREAD

**Issue by so-development** [hashicorp/terraform-aws-nomad#77]
Hi, 

I think the same issue that was reported for terraform-aws-consul (https://github.com/hashicorp/terraform-aws-consul/issues/183) also exists for nomad.

When I try to create an "aws_autoscaling_attachment" by using the autoscaling group "autoscaling_group" of the module "nomad-cluster" I experience the following behavior:

First apply: Target groups are added
Second apply: Target groups are removed
Third apply: Target groups are added
...

Regarding to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_attachment I guess the following snippet should also be added for the autoscaling group here:
```
  lifecycle {
    ignore_changes = [load_balancers, target_group_arns]
  }
```

The same change was made for terraform-aws consul here: https://github.com/hashicorp/terraform-aws-consul/pull/188

**Comment by brikis98** [comment]
Thanks for the fix in  #78!
