### ISSUE TITLE
Feature Request: Support for ARM installations

### ISSUE THREAD

**Issue by tekacs** [hashicorp/terraform-aws-nomad#80]
Nomad and Consul both have ARM64 distributions, which seem a fit for AWS' Graviton-based t/m/c/r6g instances.

Unfortunately, it looks like the install-nomad module in this repo (at the least) is [only designed for x86-64](https://github.com/hashicorp/terraform-aws-nomad/blob/e21690f83eeadc041295f67500bbfaabffe078d0/modules/install-nomad/install-nomad#L130).

I could certainly take a stab, but would it be possible to consider and add support for ARM64 to this repo, so that the modules herein can be used for deploys on those newer nodes?

**Comment by robmorgan** [comment]
Hi Amar,

It's not something we are going to prioritize on our roadmap in the near future, but we'd be more than happy to take a look at it if you want to contribute something. I would suggest adding architecture defaults and flags so its forwards compatible with any other architectures that may emerge one day. Be sure to include any relevant tests!

Regards,

Rob

**Comment by tekacs** [comment]
It seems like there's an upstream issue to be resolved first: https://github.com/hashicorp/nomad/issues/7989 so I'll wait for that to pass before taking a look at this. :)

**Comment by jaskinn** [comment]
I think that issue has recently been resolved. I think nomad v1.0.2 contains the change.
