### ISSUE TITLE
Making CIDR Block for SSH Configuration Optional and Outbound Traffic Configurable

### ISSUE THREAD

**Issue by MatthiasScholz** [hashicorp/terraform-aws-nomad#84]
Currently the CIDR blocks for incoming SSH access is mandatory.

Especially with the introduction of the AWS System Manager Session Manager an alternative administrative access is available. This would allow to reduce the access for SSH access and increase the security.

Furthermore module users might have the use case to limit the outbound traffic traffic as well.

Source Code References:
- [nomad-cluster/main.tf - SSH SG](https://github.com/hashicorp/terraform-aws-nomad/blob/10c23820707e0ef7eef9ea24f59dc67ef7046e45/modules/nomad-cluster/main.tf#L138)
- [nomad-cluster/main.tf - Outbound Traffic](https://github.com/hashicorp/terraform-aws-nomad/blob/10c23820707e0ef7eef9ea24f59dc67ef7046e45/modules/nomad-cluster/main.tf#L153)

**Comment by brikis98** [comment]
I think there may be some confusion here... As indicated in multiple places in the docs, the Terraform code in the root folder (i.e., `terraform-aws-nomad/main.tf`) and the `examples` folder are all _example code_. They are intentionally examples that are designed for easy testing and learning, but are NOT meant to be used directly in prod. The code to use in prod is the code in `modules`, the vast majority of which already allows you to configure the CIDR blocks allowed to access the cluster.

**Comment by MatthiasScholz** [comment]
Sorry for being incomplete in the issue description. Indeed the main intention was making the CIDR block in the module configurable. Changing the `main.tf` on the root level was a side effect due to testing attempt.

-> The issue description got update to better fit the intention.

**Comment by brikis98** [comment]
Understood, thanks!

**Comment by MatthiasScholz** [comment]
PR #85 merged. Closing issues as it has been resolved.
