### ISSUE TITLE
Inconsistent with consul module

### ISSUE THREAD

**Issue by dgrstl** [hashicorp/terraform-aws-nomad#9]
https://github.com/hashicorp/terraform-aws-nomad/blob/223be6dfee91b7d94464609c65ae5a43ae6a1adb/modules/nomad-cluster/main.tf#L30

Not a big deal but it would be nice if all the modules worked in more or less the way way. See https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/main.tf#L31-L35

**Comment by brikis98** [comment]
Sure, consistency seems like a good idea. Should be an easy PR fix if anyone has the time :)
