### ISSUE TITLE
Fix examples/nomad-consul-ami/nomad-consul-docker.json

### ISSUE THREAD

**Issue by harryvederci** [hashicorp/terraform-aws-nomad#90]
Hi! I have no idea what I'm doing, but I had issues using `examples/nomad-consul-ami/nomad-consul-docker.json`,
and the following made my problems go away:

Find and replace all occurrences of `clean_ami_name` with `clean_resource_name` in the file.

(I had a PR ready for this, but I don't feel like reading your CLA at the moment.)

**Comment by robmorgan** [comment]
Hi @harryvederci,

The examples you've pointed to haven't been upgraded to use the latest version of Packer. As you mentioned the solution is to replace `clean_ami_name` with `clean_resource_name` as the former is now deprecated. I'll leave this issue open for now until somebody submits a PR and signs the CLA.
